#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; BRANCH="$2"; BRANCH_DIR="$DOKKU_ROOT/$APP/DOKKU/$BRANCH" PORT="$3"; IP="$4"

set +e; NO_VHOST=$(dokku config:get $APP NO_VHOST); set -e

if [[ -n "$NO_VHOST" ]]; then
  echo "-----> NO_VHOST config detected"
elif [[ ! -f "$BRANCH_DIR/VHOST" ]]; then
  dokku domains:setup $APP $BRANCH
fi

dokku nginx:build-config $APP $BRANCH $PORT $IP
